cache:
  directories:
    - /var/cache/apt/archives/*.deb
  
language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update -qq
    
install:
  - sudo apt-get -y install qt58base qt58declarative qt58quickcontrols2 qt58svg qt58webengine qt58graphicaleffects
  - source /opt/qt58/bin/qt58-env.sh

script:
  - git clone git://code.qt.io/qt/qtwebview.git
  - cd qtwebview
  - git checkout v5.8.0
  - mkdir build && cd build
  - qmake ..
  - make
  - sudo make install
  - cd ../../
  - git clone -b develop https://github.com/lirios/fluid
  - cd fluid
  - git submodule update --init
  - ./scripts/fetch_icons.sh
  - mkdir build
  - cd build
  - qmake CONFIG+=install_under_qt ../fluid.pro
  - make -j4
  - sudo make install
  - cd ../../
  - mkdir build
  - cd build
  - qmake ..
  - make -j4
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../

after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=. -verbose=2
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=. -verbose=2
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./OurGUS*.AppImage https://transfer.sh/OurGUS-git.$(git rev-parse --short HEAD)-x86_64.AppImage

